AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: https://serverlessland.com/blog/implementing-an-event-driven-serverless-story-generation-application-with-chatgpt-and-dall-e--aws-compute-blog

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
    CodeUri: ./ # This has to be the path to the folder containing the Cargo.toml file!
  Api:
    TracingEnabled: True

Resources:
  StoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: StoryTable
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  GenerateStoryTextLambda:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - arm64

  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ./machine.asl.json
      DefinitionSubstitutions:
        StoryTable: !Sub ${StoryTable}
        GenerateStoryTextLambda: !Sub ${GenerateStoryTextLambda.Arn}
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource: !Sub ${StoryTable.Arn}
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !Sub ${GenerateStoryTextLambda.Arn}
